<?php
	session_start();
?>

<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Cadastro — EventHub</title>

    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-... (hash)" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>

<div class="container mt-5">
    <div class="col">
        <div class="card card-register">
            <div class="card-header">
                <h5 class="mb-0">Criar conta</h5>
                <small>Preencha os campos para se Cadastrar</small>
            </div>

            <div class="card-body">
                <div class="alert-area mb-3" aria-live="polite"></div>

                <form action="/usuario/salvar" method="POST" novalidate>

                    <?php if (isset($_GET['erro']) && $_GET['erro'] == 0): ?>
                        <div class="d-flex justify-content-center mb-3">
                            <div class="alert alert-danger w-100 d-flex justify-content-center align-items-center" role="alert">
                                <i class="fas fa-exclamation-circle me-2"></i>
                                Email já utilizado!
                            </div>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($_GET['erro']) && $_GET['erro'] == 1): ?>
                        <div class="d-flex justify-content-center mb-3">
                            <div class="alert alert-danger w-100 d-flex justify-content-center align-items-center" role="alert">
                                <i class="fas fa-exclamation-circle me-2"></i>
                                Senha está com menos de 8 caracteres!
                            </div>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($_GET['erro']) && $_GET['erro'] == 3): ?>
                        <div class="d-flex justify-content-center mb-3">
                            <div class="alert alert-danger w-100 d-flex justify-content-center align-items-center" role="alert">
                                <i class="fas fa-exclamation-circle me-2"></i>
                                Senha está fraca!
                            </div>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($_GET['erro']) && $_GET['erro'] == 2): ?>
                        <div class="d-flex justify-content-center mb-3">
                            <div class="alert alert-danger w-100 d-flex justify-content-center align-items-center" role="alert">
                                <i class="fas fa-exclamation-circle me-2"></i>
                                Preencha os valores corretamente!
                            </div>
                        </div>
                    <?php endif; ?>

                    <div class="mb-3">
                        <label class="form-label">Nome</label>
                        <input type="input" name="nome" class="form-control" required placeholder="Nome" />
                        <div class="invalid-feedback">Informe um nome válido.</div>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">E-mail</label>
                        <input type="email" name="email" class="form-control" required placeholder="teste@gmail.com" />
                        <div class="invalid-feedback">Informe um email válido.</div>
                    </div> 

                    <div class="mb-3">
                        <label class="form-label">Telefone</label>
                        <input type="tel" id="telefone" name="telefone" 
                        pattern="\(\d{2}\)\s\d{4,5}-\d{4}" class="form-control"  
                        placeholder="(99) 99999-9999" required>
                        <div class="invalid-feedback">Informe um telefone válido.</div>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Senha</label>
                        <div class="input-group">
                            <input type="password" name="senha" id="senha" class="form-control" required placeholder="Senha" />
                            
                        </div>
                        <div>
                            <div class="progress mt-3">

                            <div class="progress-bar" id="barra-forca" style="width:0%;"></div>
                            </div>
                            <span id="nivel-senha" style="font-weight:bold; margin-left:5px;">Muito Fraca</span>
                        </div>
                        
                    <button type="submit" class="btn btn-primary mt-3">Cadastrar-se</button>
                </form>

                <div class="mt-3 text-center small">
                    Já tem conta? <a href="/">Entrar</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

<!-- JS do projeto -->
<script src="/script.js"></script>

</body>
</html>
