<h2>Editar Usuário</h2>
<form method="post" action="/usuario/atualizar">
  <input type="hidden" name="id" value="<?= $this->view->usuario['id'] ?>">
  <input type="text" name="nome" value="<?= $this->view->usuario['nome'] ?>" class="form-control">
  <input type="email" name="email" value="<?= $this->view->usuario['email'] ?>" class="form-control">
  <input type="password" name="senha" value="<?= $this->view->usuario['senha'] ?>" class="form-control">
  <button type="submit" class="btn btn-primary mt-2">Atualizar</button>
</form>
